# Generated by Django 6.0.2 on 2026-02-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('line', models.CharField(choices=[('line1', 'Line 1'), ('line2', 'Line 2'), ('line3', 'Line 3'), ('line4', 'Line 4'), ('line5', 'Line 5'), ('line6', 'Line 6'), ('line7', 'Line 7')], max_length=10)),
                ('wo_number', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=20)),
                ('product_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('target_quantity', models.PositiveIntegerField()),
                ('hour1', models.PositiveIntegerField(default=0)),
                ('hour2', models.PositiveIntegerField(default=0)),
                ('hour3', models.PositiveIntegerField(default=0)),
                ('hour4', models.PositiveIntegerField(default=0)),
                ('hour5', models.PositiveIntegerField(default=0)),
                ('hour6', models.PositiveIntegerField(default=0)),
                ('hour7', models.PositiveIntegerField(default=0)),
                ('hour8', models.PositiveIntegerField(default=0)),
                ('hour9', models.PositiveIntegerField(default=0)),
                ('hour10', models.PositiveIntegerField(default=0)),
                ('hour11', models.PositiveIntegerField(default=0)),
                ('jar', models.PositiveIntegerField(default=0)),
                ('cap', models.PositiveIntegerField(default=0)),
                ('front_label', models.PositiveIntegerField(default=0)),
                ('back_label', models.PositiveIntegerField(default=0)),
                ('carton', models.PositiveIntegerField(default=0)),
                ('sleeve', models.PositiveIntegerField(default=0)),
                ('sticker', models.PositiveIntegerField(default=0)),
                ('tube', models.PositiveIntegerField(default=0)),
                ('packets', models.PositiveIntegerField(default=0)),
                ('roll_on_ball', models.PositiveIntegerField(default=0)),
                ('jar_pump', models.PositiveIntegerField(default=0)),
                ('operator_names', models.TextField()),
                ('supervisor_names', models.TextField()),
                ('line_captain_signature', models.CharField(max_length=100)),
                ('supervisor_signature', models.CharField(max_length=100)),
            ],
        ),
    ]
