# Generated by Django 5.2 on 2026-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], max_length=20),
        ),
    ]
