# Generated by Django 5.2 on 2026-02-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0002_alter_jobcard_id_alter_jobcard_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
