# Generated by Django 5.2 on 2026-02-13 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0003_alter_jobcard_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], max_length=20)),
                ('line', models.CharField(choices=[('line1', 'Line 1'), ('line2', 'Line 2'), ('line3', 'Line 3'), ('line4', 'Line 4'), ('line5', 'Line 5'), ('line6', 'Line 6'), ('line7', 'Line 7')], max_length=10)),
                ('aggregated_data', models.JSONField()),
                ('supervisor_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TempSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('line1', 'Line 1'), ('line2', 'Line 2'), ('line3', 'Line 3'), ('line4', 'Line 4'), ('line5', 'Line 5'), ('line6', 'Line 6'), ('line7', 'Line 7')], max_length=10)),
                ('shift', models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hour1', models.PositiveIntegerField(default=0)),
                ('hour2', models.PositiveIntegerField(default=0)),
                ('hour3', models.PositiveIntegerField(default=0)),
                ('hour4', models.PositiveIntegerField(default=0)),
                ('hour5', models.PositiveIntegerField(default=0)),
                ('hour6', models.PositiveIntegerField(default=0)),
                ('hour7', models.PositiveIntegerField(default=0)),
                ('hour8', models.PositiveIntegerField(default=0)),
                ('hour9', models.PositiveIntegerField(default=0)),
                ('hour10', models.PositiveIntegerField(default=0)),
                ('hour11', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
