# Generated by Django 5.2 on 2026-02-19 21:09

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0005_shiftsubmission_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-date', 'line']},
        ),
        migrations.AlterModelOptions(
            name='shiftsubmission',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='tempsubmission',
            options={'ordering': ['line', 'shift']},
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='line',
            field=models.CharField(choices=[('line1', 'Line 1'), ('line2', 'Line 2'), ('line3', 'Line 3'), ('line4', 'Line 4'), ('line5', 'Line 5'), ('line6', 'Line 6'), ('line7', 'Line 7')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftsubmission',
            name='aggregated_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='shiftsubmission',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='shiftsubmission',
            name='line',
            field=models.CharField(choices=[('line1', 'Line 1'), ('line2', 'Line 2'), ('line3', 'Line 3'), ('line4', 'Line 4'), ('line5', 'Line 5'), ('line6', 'Line 6'), ('line7', 'Line 7')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='shiftsubmission',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tempsubmission',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='tempsubmission',
            name='line',
            field=models.CharField(choices=[('line1', 'Line 1'), ('line2', 'Line 2'), ('line3', 'Line 3'), ('line4', 'Line 4'), ('line5', 'Line 5'), ('line6', 'Line 6'), ('line7', 'Line 7')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tempsubmission',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='jobcard',
            unique_together={('date', 'line', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='shiftsubmission',
            unique_together={('date', 'shift', 'line')},
        ),
        migrations.AlterUniqueTogether(
            name='tempsubmission',
            unique_together={('operator', 'date', 'line', 'shift')},
        ),
        migrations.AddIndex(
            model_name='tempsubmission',
            index=models.Index(fields=['date', 'shift', 'line'], name='jobcard_tem_date_744f11_idx'),
        ),
    ]
