# Generated by Django 5.2 on 2026-02-20 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0006_alter_jobcard_options_alter_shiftsubmission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='jobcard',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shiftsubmission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tempsubmission',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['date', 'line', 'shift'], name='jobcard_job_date_3ee1f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobcard',
            constraint=models.UniqueConstraint(fields=('date', 'line', 'shift'), name='unique_jobcard_per_shift_line_date'),
        ),
        migrations.AddConstraint(
            model_name='shiftsubmission',
            constraint=models.UniqueConstraint(fields=('date', 'shift', 'line'), name='unique_shift_submission'),
        ),
        migrations.AddConstraint(
            model_name='tempsubmission',
            constraint=models.UniqueConstraint(fields=('operator', 'date', 'line', 'shift'), name='unique_operator_submission'),
        ),
    ]
