# Generated by Django 5.2 on 2026-02-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0007_hourentry_alter_jobcard_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
