# Generated by Django 5.2 on 2026-02-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0008_jobcard_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='line',
            field=models.CharField(choices=[('FL001', 'FL 001'), ('FL006', 'FL 006'), ('FL007', 'FL 007'), ('FL008', 'FL 008'), ('FL009', 'FL 009'), ('FL010', 'FL 010'), ('FL013', 'FL 013'), ('FL015', 'FL 015'), ('COPACK', 'CO-PACKING')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='shiftsubmission',
            name='line',
            field=models.CharField(choices=[('FL001', 'FL 001'), ('FL006', 'FL 006'), ('FL007', 'FL 007'), ('FL008', 'FL 008'), ('FL009', 'FL 009'), ('FL010', 'FL 010'), ('FL013', 'FL 013'), ('FL015', 'FL 015'), ('COPACK', 'CO-PACKING')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tempsubmission',
            name='line',
            field=models.CharField(choices=[('FL001', 'FL 001'), ('FL006', 'FL 006'), ('FL007', 'FL 007'), ('FL008', 'FL 008'), ('FL009', 'FL 009'), ('FL010', 'FL 010'), ('FL013', 'FL 013'), ('FL015', 'FL 015'), ('COPACK', 'CO-PACKING')], db_index=True, max_length=10),
        ),
    ]
